// Code generated by protoc-gen-go. DO NOT EDIT.
// source: capsule8/api/v0/alert.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/any"
import google_protobuf3 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Alert_Severity int32

const (
	Alert_ALERT_SEVERITY_UNSPECIFIED Alert_Severity = 0
	Alert_SEVERITY_LOW               Alert_Severity = 1
	Alert_SEVERITY_MEDIUM            Alert_Severity = 2
	Alert_SEVERITY_HIGH              Alert_Severity = 3
)

var Alert_Severity_name = map[int32]string{
	0: "ALERT_SEVERITY_UNSPECIFIED",
	1: "SEVERITY_LOW",
	2: "SEVERITY_MEDIUM",
	3: "SEVERITY_HIGH",
}
var Alert_Severity_value = map[string]int32{
	"ALERT_SEVERITY_UNSPECIFIED": 0,
	"SEVERITY_LOW":               1,
	"SEVERITY_MEDIUM":            2,
	"SEVERITY_HIGH":              3,
}

func (x Alert_Severity) String() string {
	return proto.EnumName(Alert_Severity_name, int32(x))
}
func (Alert_Severity) EnumDescriptor() ([]byte, []int) { return fileDescriptor10, []int{0, 0} }

type Alert_Confidence int32

const (
	Alert_ALERT_CONFIDENCE_UNSPECIFIED Alert_Confidence = 0
	Alert_CONFIDENCE_LOW               Alert_Confidence = 1
	Alert_CONFIDENCE_MEDIUM            Alert_Confidence = 2
	Alert_CONFIDENCE_HIGH              Alert_Confidence = 3
)

var Alert_Confidence_name = map[int32]string{
	0: "ALERT_CONFIDENCE_UNSPECIFIED",
	1: "CONFIDENCE_LOW",
	2: "CONFIDENCE_MEDIUM",
	3: "CONFIDENCE_HIGH",
}
var Alert_Confidence_value = map[string]int32{
	"ALERT_CONFIDENCE_UNSPECIFIED": 0,
	"CONFIDENCE_LOW":               1,
	"CONFIDENCE_MEDIUM":            2,
	"CONFIDENCE_HIGH":              3,
}

func (x Alert_Confidence) String() string {
	return proto.EnumName(Alert_Confidence_name, int32(x))
}
func (Alert_Confidence) EnumDescriptor() ([]byte, []int) { return fileDescriptor10, []int{0, 1} }

type Alert_Entity int32

const (
	Alert_ALERT_ENTITY_UNSPECIFIED Alert_Entity = 0
	Alert_ENTITY_PROCESS           Alert_Entity = 1
	Alert_ENTITY_CONTAINER         Alert_Entity = 2
	Alert_ENTITY_NODE              Alert_Entity = 3
	Alert_ENTITY_CLUSTER           Alert_Entity = 4
)

var Alert_Entity_name = map[int32]string{
	0: "ALERT_ENTITY_UNSPECIFIED",
	1: "ENTITY_PROCESS",
	2: "ENTITY_CONTAINER",
	3: "ENTITY_NODE",
	4: "ENTITY_CLUSTER",
}
var Alert_Entity_value = map[string]int32{
	"ALERT_ENTITY_UNSPECIFIED": 0,
	"ENTITY_PROCESS":           1,
	"ENTITY_CONTAINER":         2,
	"ENTITY_NODE":              3,
	"ENTITY_CLUSTER":           4,
}

func (x Alert_Entity) String() string {
	return proto.EnumName(Alert_Entity_name, int32(x))
}
func (Alert_Entity) EnumDescriptor() ([]byte, []int) { return fileDescriptor10, []int{0, 2} }

type Alert_Scope int32

const (
	Alert_ALERT_SCOPE_UNSPECIFIED Alert_Scope = 0
	Alert_SCOPE_PROCESS           Alert_Scope = 1
	Alert_SCOPE_CONTAINER         Alert_Scope = 2
	Alert_SCOPE_NODE              Alert_Scope = 3
	Alert_SCOPE_CLUSTER           Alert_Scope = 4
)

var Alert_Scope_name = map[int32]string{
	0: "ALERT_SCOPE_UNSPECIFIED",
	1: "SCOPE_PROCESS",
	2: "SCOPE_CONTAINER",
	3: "SCOPE_NODE",
	4: "SCOPE_CLUSTER",
}
var Alert_Scope_value = map[string]int32{
	"ALERT_SCOPE_UNSPECIFIED": 0,
	"SCOPE_PROCESS":           1,
	"SCOPE_CONTAINER":         2,
	"SCOPE_NODE":              3,
	"SCOPE_CLUSTER":           4,
}

func (x Alert_Scope) String() string {
	return proto.EnumName(Alert_Scope_name, int32(x))
}
func (Alert_Scope) EnumDescriptor() ([]byte, []int) { return fileDescriptor10, []int{0, 3} }

type Alert struct {
	// Unique alert message identifier
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Timestamp of when the alert message was created
	CreateTime *google_protobuf3.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	// The type of entity where anomalous behavior was detected
	// (e.g. process, container, node, or cluster).
	Entity Alert_Entity `protobuf:"varint,3,opt,name=entity,enum=capsule8.api.v0.Alert_Entity" json:"entity,omitempty"`
	// The unique IDs of the entity where anomalous behavior was
	// detected. Exactly one of these should be non-NULL.
	ProcessId   string `protobuf:"bytes,4,opt,name=process_id,json=processId" json:"process_id,omitempty"`
	ContainerId string `protobuf:"bytes,5,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	NodeId      string `protobuf:"bytes,6,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	ClusterId   string `protobuf:"bytes,7,opt,name=cluster_id,json=clusterId" json:"cluster_id,omitempty"`
	// The scope of impact (just the process, entire container, node, or
	// cluster). This is the "blast radius" of the security impact
	// around the source of the alert.
	Scope Alert_Scope `protobuf:"varint,8,opt,name=scope,enum=capsule8.api.v0.Alert_Scope" json:"scope,omitempty"`
	// Unique identifier of the Strategy that generated the alert
	StrategyId string `protobuf:"bytes,9,opt,name=strategy_id,json=strategyId" json:"strategy_id,omitempty"`
	// Confidence in the event as determined by the Strategy that generated
	// the alert
	StrategyConfidence Alert_Confidence `protobuf:"varint,10,opt,name=strategy_confidence,json=strategyConfidence,enum=capsule8.api.v0.Alert_Confidence" json:"strategy_confidence,omitempty"`
	// Severity of the event as determined by the Strategy that generated
	// the alert
	StrategySeverity Alert_Severity `protobuf:"varint,11,opt,name=strategy_severity,json=strategySeverity,enum=capsule8.api.v0.Alert_Severity" json:"strategy_severity,omitempty"`
	// Confidence in the alert as determined by the Arbiter
	Confidence Alert_Confidence `protobuf:"varint,12,opt,name=confidence,enum=capsule8.api.v0.Alert_Confidence" json:"confidence,omitempty"`
	// Severity of the alert as determined by the Arbiter
	Severity Alert_Severity `protobuf:"varint,13,opt,name=severity,enum=capsule8.api.v0.Alert_Severity" json:"severity,omitempty"`
	// Optional; Additional details defined by the Strategy that
	// generated the alert or the Arbiter. These are less strictly
	// defined and intended for display to the user in the CLI or
	// Console. The details field is invisible to NYQL queries.
	Details *google_protobuf1.Any `protobuf:"bytes,100,opt,name=details" json:"details,omitempty"`
}

func (m *Alert) Reset()                    { *m = Alert{} }
func (m *Alert) String() string            { return proto.CompactTextString(m) }
func (*Alert) ProtoMessage()               {}
func (*Alert) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{0} }

func (m *Alert) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Alert) GetCreateTime() *google_protobuf3.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Alert) GetEntity() Alert_Entity {
	if m != nil {
		return m.Entity
	}
	return Alert_ALERT_ENTITY_UNSPECIFIED
}

func (m *Alert) GetProcessId() string {
	if m != nil {
		return m.ProcessId
	}
	return ""
}

func (m *Alert) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *Alert) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Alert) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *Alert) GetScope() Alert_Scope {
	if m != nil {
		return m.Scope
	}
	return Alert_ALERT_SCOPE_UNSPECIFIED
}

func (m *Alert) GetStrategyId() string {
	if m != nil {
		return m.StrategyId
	}
	return ""
}

func (m *Alert) GetStrategyConfidence() Alert_Confidence {
	if m != nil {
		return m.StrategyConfidence
	}
	return Alert_ALERT_CONFIDENCE_UNSPECIFIED
}

func (m *Alert) GetStrategySeverity() Alert_Severity {
	if m != nil {
		return m.StrategySeverity
	}
	return Alert_ALERT_SEVERITY_UNSPECIFIED
}

func (m *Alert) GetConfidence() Alert_Confidence {
	if m != nil {
		return m.Confidence
	}
	return Alert_ALERT_CONFIDENCE_UNSPECIFIED
}

func (m *Alert) GetSeverity() Alert_Severity {
	if m != nil {
		return m.Severity
	}
	return Alert_ALERT_SEVERITY_UNSPECIFIED
}

func (m *Alert) GetDetails() *google_protobuf1.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*Alert)(nil), "capsule8.api.v0.Alert")
	proto.RegisterEnum("capsule8.api.v0.Alert_Severity", Alert_Severity_name, Alert_Severity_value)
	proto.RegisterEnum("capsule8.api.v0.Alert_Confidence", Alert_Confidence_name, Alert_Confidence_value)
	proto.RegisterEnum("capsule8.api.v0.Alert_Entity", Alert_Entity_name, Alert_Entity_value)
	proto.RegisterEnum("capsule8.api.v0.Alert_Scope", Alert_Scope_name, Alert_Scope_value)
}

func init() { proto.RegisterFile("capsule8/api/v0/alert.proto", fileDescriptor10) }

var fileDescriptor10 = []byte{
	// 611 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xd1, 0x4f, 0xda, 0x50,
	0x14, 0xc6, 0x07, 0x0a, 0xe2, 0x41, 0xa1, 0x1e, 0x5d, 0xec, 0x10, 0x27, 0xf2, 0xe4, 0x53, 0x31,
	0x2e, 0x4b, 0x96, 0xf8, 0xc4, 0xca, 0x75, 0x36, 0xc1, 0x62, 0x2e, 0x75, 0xcb, 0xf6, 0x42, 0x6a,
	0xef, 0x95, 0x35, 0xc1, 0xb6, 0x69, 0x2f, 0x26, 0xfc, 0xcb, 0xfb, 0x2b, 0x96, 0xde, 0xb6, 0xd7,
	0x06, 0x43, 0xe2, 0x23, 0xbf, 0xf3, 0x9d, 0xef, 0xfb, 0x7a, 0x28, 0xc0, 0x89, 0xe7, 0x46, 0xc9,
	0x72, 0xc1, 0xbf, 0x0d, 0xdc, 0xc8, 0x1f, 0xbc, 0x5c, 0x0e, 0xdc, 0x05, 0x8f, 0x85, 0x11, 0xc5,
	0xa1, 0x08, 0xb1, 0x5d, 0x0c, 0x0d, 0x37, 0xf2, 0x8d, 0x97, 0xcb, 0xce, 0xa7, 0x79, 0x18, 0xce,
	0x17, 0x7c, 0x20, 0xc7, 0x8f, 0xcb, 0xa7, 0x81, 0x1b, 0xac, 0x32, 0x6d, 0xe7, 0x6c, 0x7d, 0x24,
	0xfc, 0x67, 0x9e, 0x08, 0xf7, 0x39, 0xca, 0x04, 0xfd, 0x7f, 0x0d, 0xa8, 0x0d, 0x53, 0x73, 0x6c,
	0x41, 0xd5, 0x67, 0x7a, 0xa5, 0x57, 0xb9, 0xd8, 0xa5, 0x55, 0x9f, 0xe1, 0x35, 0x34, 0xbd, 0x98,
	0xbb, 0x82, 0xcf, 0xd2, 0x1d, 0xbd, 0xda, 0xab, 0x5c, 0x34, 0xaf, 0x3a, 0x46, 0x66, 0x68, 0x14,
	0x86, 0x86, 0x53, 0x18, 0x52, 0xc8, 0xe4, 0x29, 0xc0, 0xaf, 0x50, 0xe7, 0x81, 0xf0, 0xc5, 0x4a,
	0xdf, 0xea, 0x55, 0x2e, 0x5a, 0x57, 0xa7, 0xc6, 0x5a, 0x69, 0x43, 0x86, 0x1a, 0x44, 0x8a, 0x68,
	0x2e, 0xc6, 0x53, 0x80, 0x28, 0x0e, 0x3d, 0x9e, 0x24, 0x33, 0x9f, 0xe9, 0xdb, 0xb2, 0xcb, 0x6e,
	0x4e, 0x2c, 0x86, 0xe7, 0xb0, 0xe7, 0x85, 0x81, 0x70, 0xfd, 0x80, 0xc7, 0xa9, 0xa0, 0x26, 0x05,
	0x4d, 0xc5, 0x2c, 0x86, 0xc7, 0xb0, 0x13, 0x84, 0x8c, 0xa7, 0xd3, 0xba, 0x9c, 0xd6, 0xd3, 0x8f,
	0x16, 0x4b, 0xad, 0xbd, 0xc5, 0x32, 0x11, 0xd9, 0xe6, 0x4e, 0x66, 0x9d, 0x13, 0x8b, 0xe1, 0x15,
	0xd4, 0x12, 0x2f, 0x8c, 0xb8, 0xde, 0x90, 0x7d, 0xbb, 0x1b, 0xfa, 0x4e, 0x53, 0x0d, 0xcd, 0xa4,
	0x78, 0x06, 0xcd, 0x44, 0xc4, 0xae, 0xe0, 0xf3, 0x55, 0xea, 0xb9, 0x2b, 0x3d, 0xa1, 0x40, 0x16,
	0x43, 0x0a, 0x87, 0x4a, 0xe0, 0x85, 0xc1, 0x93, 0xcf, 0x78, 0xe0, 0x71, 0x1d, 0x64, 0xc4, 0xf9,
	0x86, 0x08, 0x53, 0x09, 0x29, 0x16, 0xdb, 0xaf, 0x0c, 0xc7, 0x70, 0xa0, 0x3c, 0x13, 0xfe, 0xc2,
	0xe3, 0xf4, 0xc8, 0x4d, 0xe9, 0x78, 0xb6, 0xa9, 0x74, 0x2e, 0xa3, 0x5a, 0xb1, 0x59, 0x10, 0x1c,
	0x02, 0x94, 0x8a, 0xed, 0xbd, 0xb7, 0x58, 0x69, 0x09, 0xaf, 0xa1, 0xa1, 0x7a, 0xec, 0xbf, 0xaf,
	0x87, 0x5a, 0x40, 0x03, 0x76, 0x18, 0x17, 0xae, 0xbf, 0x48, 0x74, 0x26, 0x5f, 0xb0, 0xa3, 0x37,
	0x2f, 0xd8, 0x30, 0x58, 0xd1, 0x42, 0xd4, 0x67, 0xd0, 0x50, 0xdd, 0x3f, 0x43, 0x67, 0x38, 0x26,
	0xd4, 0x99, 0x4d, 0xc9, 0x4f, 0x42, 0x2d, 0xe7, 0xf7, 0xec, 0xc1, 0x9e, 0xde, 0x13, 0xd3, 0xba,
	0xb1, 0xc8, 0x48, 0xfb, 0x80, 0x1a, 0xec, 0xa9, 0xc9, 0x78, 0xf2, 0x4b, 0xab, 0xe0, 0x21, 0xb4,
	0x15, 0xb9, 0x23, 0x23, 0xeb, 0xe1, 0x4e, 0xab, 0xe2, 0x01, 0xec, 0x2b, 0x78, 0x6b, 0xfd, 0xb8,
	0xd5, 0xb6, 0xfa, 0x01, 0x40, 0xe9, 0xe2, 0x3d, 0xe8, 0x66, 0x39, 0xe6, 0xc4, 0xbe, 0xb1, 0x46,
	0xc4, 0x36, 0xc9, 0x5a, 0x12, 0x42, 0xab, 0x34, 0xcb, 0xb2, 0x3e, 0xc2, 0x41, 0x89, 0xa9, 0xb4,
	0x43, 0x68, 0x97, 0x70, 0x9e, 0xb7, 0x84, 0x7a, 0xf6, 0x43, 0xc0, 0x2e, 0xe8, 0x59, 0x16, 0xb1,
	0x9d, 0xb7, 0x4f, 0x84, 0xd0, 0xca, 0xf9, 0x3d, 0x9d, 0x98, 0x64, 0x3a, 0xd5, 0x2a, 0x78, 0x04,
	0x5a, 0xce, 0xcc, 0x89, 0xed, 0x0c, 0x2d, 0x9b, 0x50, 0xad, 0x8a, 0x6d, 0x68, 0xe6, 0xd4, 0x9e,
	0x8c, 0x88, 0xb6, 0x55, 0x5a, 0x35, 0xc7, 0x0f, 0x53, 0x87, 0x50, 0x6d, 0xbb, 0x1f, 0x42, 0x4d,
	0xbe, 0xcf, 0x78, 0x02, 0xc7, 0xf9, 0x25, 0xcd, 0xc9, 0xfd, 0xfa, 0xc3, 0xa5, 0xf7, 0x91, 0xf8,
	0x35, 0x33, 0xbd, 0xa3, 0x44, 0xe5, 0xc8, 0x16, 0x40, 0x06, 0xf3, 0x44, 0xb5, 0xa7, 0x02, 0xbf,
	0x77, 0xff, 0x74, 0xe6, 0xbe, 0xf8, 0xbb, 0x7c, 0x34, 0xbc, 0xf0, 0x79, 0xb0, 0xf6, 0x1f, 0xf7,
	0x58, 0x97, 0x5f, 0xf9, 0x97, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x8d, 0x48, 0x22, 0xfd,
	0x04, 0x00, 0x00,
}
