// Code generated by protoc-gen-go. DO NOT EDIT.
// source: capsule8/api/v0/pubsub_service.proto

/*
Package v0 is a generated protocol buffer package.

It is generated from these files:
	capsule8/api/v0/pubsub_service.proto
	capsule8/api/v0/types.proto
	capsule8/api/v0/config_service.proto
	capsule8/api/v0/nyql_service.proto
	capsule8/api/v0/config.proto
	capsule8/api/v0/subscription.proto
	capsule8/api/v0/event.proto
	capsule8/api/v0/telemetry_service.proto
	capsule8/api/v0/capsulator_service.proto
	capsule8/api/v0/expression.proto
	capsule8/api/v0/ack.proto
	capsule8/api/v0/alert.proto

It has these top-level messages:
	PublishRequest
	PublishResponse
	FailedMessage
	PullRequest
	PullResponse
	ReceivedMessage
	AcknowledgeRequest
	AcknowledgeResponse
	IPv4Address
	IPv4AddressAndPort
	IPv6Address
	IPv6AddressAndPort
	NetworkAddress
	CreateConfigRequest
	CreateConfigResponse
	GetConfigRequest
	GetConfigResponse
	WatchConfigRequest
	WatchConfigResponse
	ListConfigsRequest
	ListConfigsResponse
	CreateSubscriptionRequest
	CreateSubscriptionResponse
	Config
	Subscription
	ContainerFilter
	EventFilter
	SyscallEventFilter
	ProcessEventFilter
	FileEventFilter
	KernelFunctionCallFilter
	NetworkEventFilter
	ContainerEventFilter
	ChargenEventFilter
	TickerEventFilter
	Modifier
	ThrottleModifier
	LimitModifier
	Event
	ChargenEvent
	TickerEvent
	ContainerEvent
	ProcessEvent
	SyscallEvent
	FileEvent
	Process
	KernelFunctionCallEvent
	NetworkEvent
	GetEventsRequest
	GetEventsResponse
	TelemetryEvent
	ListCapsulatorsRequest
	ListCapsulatorsResponse
	CreateCapsulatorRequest
	CreateCapsulatorResponse
	Capsulator
	Value
	BinaryOp
	Expression
	Ack
	Alert
*/
package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Publishes a message to topic
type PublishRequest struct {
	Topic string `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
	// Can publish one or more message(s) at a time
	Messages [][]byte `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (m *PublishRequest) Reset()                    { *m = PublishRequest{} }
func (m *PublishRequest) String() string            { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()               {}
func (*PublishRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PublishRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PublishRequest) GetMessages() [][]byte {
	if m != nil {
		return m.Messages
	}
	return nil
}

// PublishResponse returns any failed messages
type PublishResponse struct {
	FailedMessages []*FailedMessage `protobuf:"bytes,1,rep,name=failed_messages,json=failedMessages" json:"failed_messages,omitempty"`
}

func (m *PublishResponse) Reset()                    { *m = PublishResponse{} }
func (m *PublishResponse) String() string            { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()               {}
func (*PublishResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PublishResponse) GetFailedMessages() []*FailedMessage {
	if m != nil {
		return m.FailedMessages
	}
	return nil
}

type FailedMessage struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *FailedMessage) Reset()                    { *m = FailedMessage{} }
func (m *FailedMessage) String() string            { return proto.CompactTextString(m) }
func (*FailedMessage) ProtoMessage()               {}
func (*FailedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FailedMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *FailedMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// Pull messages off a topic
type PullRequest struct {
	// Must be set on first request and omitted in subsequent requests
	Topic string `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
	// Optional, timeout in milliseconds
	Timeout int64 `protobuf:"varint,2,opt,name=timeout" json:"timeout,omitempty"`
}

func (m *PullRequest) Reset()                    { *m = PullRequest{} }
func (m *PullRequest) String() string            { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()               {}
func (*PullRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PullRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PullRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type PullResponse struct {
	Messages []*ReceivedMessage `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
}

func (m *PullResponse) Reset()                    { *m = PullResponse{} }
func (m *PullResponse) String() string            { return proto.CompactTextString(m) }
func (*PullResponse) ProtoMessage()               {}
func (*PullResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PullResponse) GetMessages() []*ReceivedMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

type ReceivedMessage struct {
	Ack     []byte `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Optional, timestamp that the pubsub backend received the message
	// NOTE: some pubsub backends do not support timestamps in the messaging
	// protocol (ie. NATS)
	PublishTimeMicros int64 `protobuf:"varint,3,opt,name=publish_time_micros,json=publishTimeMicros" json:"publish_time_micros,omitempty"`
}

func (m *ReceivedMessage) Reset()                    { *m = ReceivedMessage{} }
func (m *ReceivedMessage) String() string            { return proto.CompactTextString(m) }
func (*ReceivedMessage) ProtoMessage()               {}
func (*ReceivedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReceivedMessage) GetAck() []byte {
	if m != nil {
		return m.Ack
	}
	return nil
}

func (m *ReceivedMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ReceivedMessage) GetPublishTimeMicros() int64 {
	if m != nil {
		return m.PublishTimeMicros
	}
	return 0
}

type AcknowledgeRequest struct {
	Acks [][]byte `protobuf:"bytes,1,rep,name=acks,proto3" json:"acks,omitempty"`
}

func (m *AcknowledgeRequest) Reset()                    { *m = AcknowledgeRequest{} }
func (m *AcknowledgeRequest) String() string            { return proto.CompactTextString(m) }
func (*AcknowledgeRequest) ProtoMessage()               {}
func (*AcknowledgeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AcknowledgeRequest) GetAcks() [][]byte {
	if m != nil {
		return m.Acks
	}
	return nil
}

type AcknowledgeResponse struct {
	FailedAcks [][]byte `protobuf:"bytes,1,rep,name=failed_acks,json=failedAcks,proto3" json:"failed_acks,omitempty"`
}

func (m *AcknowledgeResponse) Reset()                    { *m = AcknowledgeResponse{} }
func (m *AcknowledgeResponse) String() string            { return proto.CompactTextString(m) }
func (*AcknowledgeResponse) ProtoMessage()               {}
func (*AcknowledgeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AcknowledgeResponse) GetFailedAcks() [][]byte {
	if m != nil {
		return m.FailedAcks
	}
	return nil
}

func init() {
	proto.RegisterType((*PublishRequest)(nil), "capsule8.api.v0.PublishRequest")
	proto.RegisterType((*PublishResponse)(nil), "capsule8.api.v0.PublishResponse")
	proto.RegisterType((*FailedMessage)(nil), "capsule8.api.v0.FailedMessage")
	proto.RegisterType((*PullRequest)(nil), "capsule8.api.v0.PullRequest")
	proto.RegisterType((*PullResponse)(nil), "capsule8.api.v0.PullResponse")
	proto.RegisterType((*ReceivedMessage)(nil), "capsule8.api.v0.ReceivedMessage")
	proto.RegisterType((*AcknowledgeRequest)(nil), "capsule8.api.v0.AcknowledgeRequest")
	proto.RegisterType((*AcknowledgeResponse)(nil), "capsule8.api.v0.AcknowledgeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PubsubService service

type PubsubServiceClient interface {
	// Publishes messages to a topic
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	// Pulls messages off of a topic
	Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (PubsubService_PullClient, error)
	Acknowledge(ctx context.Context, in *AcknowledgeRequest, opts ...grpc.CallOption) (*AcknowledgeResponse, error)
}

type pubsubServiceClient struct {
	cc *grpc.ClientConn
}

func NewPubsubServiceClient(cc *grpc.ClientConn) PubsubServiceClient {
	return &pubsubServiceClient{cc}
}

func (c *pubsubServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := grpc.Invoke(ctx, "/capsule8.api.v0.PubsubService/Publish", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubsubServiceClient) Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (PubsubService_PullClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PubsubService_serviceDesc.Streams[0], c.cc, "/capsule8.api.v0.PubsubService/Pull", opts...)
	if err != nil {
		return nil, err
	}
	x := &pubsubServicePullClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PubsubService_PullClient interface {
	Recv() (*PullResponse, error)
	grpc.ClientStream
}

type pubsubServicePullClient struct {
	grpc.ClientStream
}

func (x *pubsubServicePullClient) Recv() (*PullResponse, error) {
	m := new(PullResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pubsubServiceClient) Acknowledge(ctx context.Context, in *AcknowledgeRequest, opts ...grpc.CallOption) (*AcknowledgeResponse, error) {
	out := new(AcknowledgeResponse)
	err := grpc.Invoke(ctx, "/capsule8.api.v0.PubsubService/Acknowledge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PubsubService service

type PubsubServiceServer interface {
	// Publishes messages to a topic
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	// Pulls messages off of a topic
	Pull(*PullRequest, PubsubService_PullServer) error
	Acknowledge(context.Context, *AcknowledgeRequest) (*AcknowledgeResponse, error)
}

func RegisterPubsubServiceServer(s *grpc.Server, srv PubsubServiceServer) {
	s.RegisterService(&_PubsubService_serviceDesc, srv)
}

func _PubsubService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubsubServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/capsule8.api.v0.PubsubService/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubsubServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubsubService_Pull_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PubsubServiceServer).Pull(m, &pubsubServicePullServer{stream})
}

type PubsubService_PullServer interface {
	Send(*PullResponse) error
	grpc.ServerStream
}

type pubsubServicePullServer struct {
	grpc.ServerStream
}

func (x *pubsubServicePullServer) Send(m *PullResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PubsubService_Acknowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubsubServiceServer).Acknowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/capsule8.api.v0.PubsubService/Acknowledge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubsubServiceServer).Acknowledge(ctx, req.(*AcknowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PubsubService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "capsule8.api.v0.PubsubService",
	HandlerType: (*PubsubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _PubsubService_Publish_Handler,
		},
		{
			MethodName: "Acknowledge",
			Handler:    _PubsubService_Acknowledge_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Pull",
			Handler:       _PubsubService_Pull_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "capsule8/api/v0/pubsub_service.proto",
}

func init() { proto.RegisterFile("capsule8/api/v0/pubsub_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0xe3, 0x42, 0x60, 0xe2, 0x36, 0x74, 0x83, 0x90, 0xb1, 0x02, 0xb5, 0x96, 0x1e, 0xa2,
	0x1e, 0xec, 0xa8, 0x48, 0x08, 0x55, 0x20, 0xd4, 0x1e, 0xe0, 0x42, 0xa5, 0xc8, 0x70, 0xea, 0x25,
	0xac, 0x37, 0x5b, 0x77, 0xf1, 0xcf, 0x1a, 0xaf, 0x1d, 0x84, 0x10, 0x17, 0x5e, 0x81, 0xc7, 0xe2,
	0xc8, 0x2b, 0xf0, 0x20, 0xc8, 0xbb, 0x4e, 0xea, 0xc4, 0xb4, 0x27, 0xef, 0x78, 0xbe, 0xd9, 0xf9,
	0xbe, 0x6f, 0x66, 0xe1, 0x90, 0x92, 0x5c, 0x56, 0x09, 0x7b, 0xe9, 0x93, 0x9c, 0xfb, 0xcb, 0xa9,
	0x9f, 0x57, 0xa1, 0xac, 0xc2, 0xb9, 0x64, 0xc5, 0x92, 0x53, 0xe6, 0xe5, 0x85, 0x28, 0x05, 0x1a,
	0xae, 0x50, 0x1e, 0xc9, 0xb9, 0xb7, 0x9c, 0x3a, 0xe3, 0x48, 0x88, 0x28, 0x61, 0xaa, 0x88, 0x64,
	0x99, 0x28, 0x49, 0xc9, 0x45, 0x26, 0x35, 0x1c, 0x9f, 0xc1, 0xde, 0xac, 0x0a, 0x13, 0x2e, 0xaf,
	0x02, 0xf6, 0xa5, 0x62, 0xb2, 0x44, 0x0f, 0xe1, 0x4e, 0x29, 0x72, 0x4e, 0x6d, 0xc3, 0x35, 0x26,
	0xf7, 0x03, 0x1d, 0x20, 0x07, 0xee, 0xa5, 0x4c, 0x4a, 0x12, 0x31, 0x69, 0xf7, 0x5c, 0x73, 0x62,
	0x05, 0xeb, 0x18, 0x5f, 0xc0, 0x70, 0x7d, 0x87, 0xcc, 0x45, 0x26, 0x19, 0x7a, 0x07, 0xc3, 0x4b,
	0xc2, 0x13, 0xb6, 0x98, 0xaf, 0xab, 0x0c, 0xd7, 0x9c, 0x0c, 0x8e, 0x9f, 0x7a, 0x5b, 0xfc, 0xbc,
	0xb7, 0x0a, 0x77, 0xae, 0x61, 0xc1, 0xde, 0x65, 0x3b, 0x94, 0xf8, 0x0d, 0xec, 0x6e, 0x00, 0x90,
	0x0d, 0xfd, 0x9c, 0x7c, 0x4b, 0x04, 0x59, 0x28, 0x82, 0x56, 0xb0, 0x0a, 0x6b, 0xe2, 0xac, 0x28,
	0x44, 0x61, 0xf7, 0x34, 0x71, 0x15, 0xe0, 0xd7, 0x30, 0x98, 0x55, 0x49, 0x72, 0xbb, 0x3a, 0x1b,
	0xfa, 0x25, 0x4f, 0x99, 0xa8, 0x4a, 0x55, 0x6c, 0x06, 0xab, 0x10, 0xbf, 0x07, 0x4b, 0x97, 0x37,
	0xc2, 0x5e, 0xb5, 0x7c, 0xd0, 0x8a, 0xdc, 0x8e, 0xa2, 0x80, 0x51, 0xc6, 0x97, 0xd7, 0x9a, 0xae,
	0x9d, 0x4a, 0x61, 0xb8, 0x95, 0x44, 0x0f, 0xc0, 0x24, 0x34, 0x6e, 0xb4, 0xd4, 0xc7, 0xb6, 0xc2,
	0xde, 0xa6, 0x42, 0x0f, 0x46, 0xb9, 0x36, 0x7a, 0x5e, 0xf3, 0x9b, 0xa7, 0x9c, 0x16, 0x42, 0xda,
	0xa6, 0xa2, 0xbc, 0xdf, 0xa4, 0x3e, 0xf2, 0x94, 0x9d, 0xab, 0x04, 0x9e, 0x00, 0x3a, 0xa5, 0x71,
	0x26, 0xbe, 0x26, 0x6c, 0x11, 0xb1, 0x95, 0x05, 0x08, 0x76, 0x08, 0x8d, 0x35, 0x7d, 0x2b, 0x50,
	0x67, 0xfc, 0x02, 0x46, 0x1b, 0xc8, 0x46, 0xed, 0x01, 0x0c, 0x9a, 0x31, 0xb6, 0x2a, 0x40, 0xff,
	0x3a, 0xa5, 0xb1, 0x3c, 0xfe, 0xdd, 0x83, 0xdd, 0x99, 0x5a, 0xc3, 0x0f, 0x7a, 0x0b, 0xd1, 0x67,
	0xe8, 0x37, 0xcb, 0x80, 0x0e, 0x3a, 0xce, 0x6c, 0xae, 0x9a, 0xe3, 0xde, 0x0c, 0xd0, 0x04, 0xf0,
	0xf8, 0xe7, 0x9f, 0xbf, 0xbf, 0x7a, 0x8f, 0xf0, 0x7e, 0xbd, 0xef, 0x6a, 0x56, 0xfe, 0x77, 0xf5,
	0xf9, 0x71, 0x62, 0x1c, 0xa1, 0x4f, 0xb0, 0x53, 0x0f, 0x07, 0x8d, 0xff, 0x73, 0xcf, 0x7a, 0xe4,
	0xce, 0x93, 0x1b, 0xb2, 0x4d, 0x8b, 0xc7, 0xaa, 0xc5, 0x08, 0x75, 0x5b, 0x4c, 0x0d, 0x94, 0xc0,
	0xa0, 0xe5, 0x0b, 0x7a, 0xd6, 0xb9, 0xaa, 0xeb, 0xaf, 0x73, 0x78, 0x3b, 0xa8, 0x69, 0x8b, 0x54,
	0x5b, 0x0b, 0xf7, 0xeb, 0xb6, 0x84, 0xc6, 0x27, 0xc6, 0xd1, 0xd9, 0xf8, 0xc2, 0x89, 0x78, 0x79,
	0x55, 0x85, 0x1e, 0x15, 0xa9, 0xbf, 0xf5, 0xdc, 0xc3, 0xbb, 0xea, 0xc5, 0x3e, 0xff, 0x17, 0x00,
	0x00, 0xff, 0xff, 0xef, 0xda, 0x40, 0x4e, 0x08, 0x04, 0x00, 0x00,
}
