// Code generated by protoc-gen-go. DO NOT EDIT.
// source: capsule8/api/v0/subscription.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ContainerEventView int32

const (
	// Default view of a ContainerEvent includes just basic information
	ContainerEventView_BASIC ContainerEventView = 0
	// Full view of a ContainerEvent includes raw Docker and OCI config JSON
	ContainerEventView_FULL ContainerEventView = 1
)

var ContainerEventView_name = map[int32]string{
	0: "BASIC",
	1: "FULL",
}
var ContainerEventView_value = map[string]int32{
	"BASIC": 0,
	"FULL":  1,
}

func (x ContainerEventView) String() string {
	return proto.EnumName(ContainerEventView_name, int32(x))
}
func (ContainerEventView) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

type ProcessView int32

const (
	// Default process view of an event includes just basic process information
	ProcessView_PROCESS_VIEW_BASIC ProcessView = 0
	// Full processview of an event includes process ancestory
	ProcessView_PROCESS_VIEW_FULL ProcessView = 1
)

var ProcessView_name = map[int32]string{
	0: "PROCESS_VIEW_BASIC",
	1: "PROCESS_VIEW_FULL",
}
var ProcessView_value = map[string]int32{
	"PROCESS_VIEW_BASIC": 0,
	"PROCESS_VIEW_FULL":  1,
}

func (x ProcessView) String() string {
	return proto.EnumName(ProcessView_name, int32(x))
}
func (ProcessView) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

type ThrottleModifier_IntervalType int32

const (
	ThrottleModifier_MILLISECOND ThrottleModifier_IntervalType = 0
	ThrottleModifier_SECOND      ThrottleModifier_IntervalType = 1
	ThrottleModifier_MINUTE      ThrottleModifier_IntervalType = 2
	ThrottleModifier_HOUR        ThrottleModifier_IntervalType = 3
)

var ThrottleModifier_IntervalType_name = map[int32]string{
	0: "MILLISECOND",
	1: "SECOND",
	2: "MINUTE",
	3: "HOUR",
}
var ThrottleModifier_IntervalType_value = map[string]int32{
	"MILLISECOND": 0,
	"SECOND":      1,
	"MINUTE":      2,
	"HOUR":        3,
}

func (x ThrottleModifier_IntervalType) String() string {
	return proto.EnumName(ThrottleModifier_IntervalType_name, int32(x))
}
func (ThrottleModifier_IntervalType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor5, []int{11, 0}
}

//
// Subscription identifies a subscriber's interest in events. The optional
// Filter field restricts the subscription to the nodes and processes
// specified within. The optional Selector field specifies the types and
// properties of the events desired by the subscriber.
//
type Subscription struct {
	// Return events matching one or more of the specified event
	// filters. If no event filters are specified, then no events
	// will be returned.
	EventFilter *EventFilter `protobuf:"bytes,1,opt,name=event_filter,json=eventFilter" json:"event_filter,omitempty"`
	// If not empty, then only return events from containers matched
	// by one or more of the specified container filters.
	ContainerFilter *ContainerFilter `protobuf:"bytes,2,opt,name=container_filter,json=containerFilter" json:"container_filter,omitempty"`
	// If not empty, then only return events from Sensors matched by
	// one or more of the specified sensor filters.
	SensorFilter *SensorFilter `protobuf:"bytes,3,opt,name=sensor_filter,json=sensorFilter" json:"sensor_filter,omitempty"`
	// If not empty, then only return events that occurred after
	// the specified relative duration subtracted from the current
	// time (recorder time). If the resulting time is in the past, then the
	// subscription will search for historic events before streaming
	// live ones.
	SinceDuration *google_protobuf1.Int64Value `protobuf:"bytes,10,opt,name=since_duration,json=sinceDuration" json:"since_duration,omitempty"`
	// If not empty, then only return events that occurred before
	// the specified relative duration added to `since_duration`.
	// If `since_duration` is not supplied, return events from now and until
	// the specified relative duration is hit.
	ForDuration *google_protobuf1.Int64Value `protobuf:"bytes,11,opt,name=for_duration,json=forDuration" json:"for_duration,omitempty"`
	// If not empty, apply the specified modifier to the subscription.
	Modifier *Modifier `protobuf:"bytes,20,opt,name=modifier" json:"modifier,omitempty"`
	// If PROCESS_VIEW_FULL, every event will include additional process
	// ancestry context.
	ProcessView ProcessView `protobuf:"varint,30,opt,name=process_view,json=processView,enum=capsule8.api.v0.ProcessView" json:"process_view,omitempty"`
}

func (m *Subscription) Reset()                    { *m = Subscription{} }
func (m *Subscription) String() string            { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()               {}
func (*Subscription) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *Subscription) GetEventFilter() *EventFilter {
	if m != nil {
		return m.EventFilter
	}
	return nil
}

func (m *Subscription) GetContainerFilter() *ContainerFilter {
	if m != nil {
		return m.ContainerFilter
	}
	return nil
}

func (m *Subscription) GetSensorFilter() *SensorFilter {
	if m != nil {
		return m.SensorFilter
	}
	return nil
}

func (m *Subscription) GetSinceDuration() *google_protobuf1.Int64Value {
	if m != nil {
		return m.SinceDuration
	}
	return nil
}

func (m *Subscription) GetForDuration() *google_protobuf1.Int64Value {
	if m != nil {
		return m.ForDuration
	}
	return nil
}

func (m *Subscription) GetModifier() *Modifier {
	if m != nil {
		return m.Modifier
	}
	return nil
}

func (m *Subscription) GetProcessView() ProcessView {
	if m != nil {
		return m.ProcessView
	}
	return ProcessView_PROCESS_VIEW_BASIC
}

type SensorFilter struct {
}

func (m *SensorFilter) Reset()                    { *m = SensorFilter{} }
func (m *SensorFilter) String() string            { return proto.CompactTextString(m) }
func (*SensorFilter) ProtoMessage()               {}
func (*SensorFilter) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

type ContainerFilter struct {
	Ids      []string `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
	Names    []string `protobuf:"bytes,2,rep,name=names" json:"names,omitempty"`
	ImageIds []string `protobuf:"bytes,3,rep,name=image_ids,json=imageIds" json:"image_ids,omitempty"`
	// Container image name (shell-style globs are supported)
	ImageNames []string `protobuf:"bytes,4,rep,name=image_names,json=imageNames" json:"image_names,omitempty"`
}

func (m *ContainerFilter) Reset()                    { *m = ContainerFilter{} }
func (m *ContainerFilter) String() string            { return proto.CompactTextString(m) }
func (*ContainerFilter) ProtoMessage()               {}
func (*ContainerFilter) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *ContainerFilter) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ContainerFilter) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *ContainerFilter) GetImageIds() []string {
	if m != nil {
		return m.ImageIds
	}
	return nil
}

func (m *ContainerFilter) GetImageNames() []string {
	if m != nil {
		return m.ImageNames
	}
	return nil
}

type EventFilter struct {
	//
	// Kernel-level events
	//
	SyscallEvents []*SyscallEventFilter `protobuf:"bytes,1,rep,name=syscall_events,json=syscallEvents" json:"syscall_events,omitempty"`
	ProcessEvents []*ProcessEventFilter `protobuf:"bytes,2,rep,name=process_events,json=processEvents" json:"process_events,omitempty"`
	FileEvents    []*FileEventFilter    `protobuf:"bytes,3,rep,name=file_events,json=fileEvents" json:"file_events,omitempty"`
	//
	// Operating System-level events (containers, etc)
	//
	ContainerEvents []*ContainerEventFilter `protobuf:"bytes,10,rep,name=container_events,json=containerEvents" json:"container_events,omitempty"`
	//
	// Debugging events (>= 100)
	//
	ChargenEvents []*ChargenEventFilter `protobuf:"bytes,100,rep,name=chargen_events,json=chargenEvents" json:"chargen_events,omitempty"`
	TickerEvents  []*TickerEventFilter  `protobuf:"bytes,101,rep,name=ticker_events,json=tickerEvents" json:"ticker_events,omitempty"`
}

func (m *EventFilter) Reset()                    { *m = EventFilter{} }
func (m *EventFilter) String() string            { return proto.CompactTextString(m) }
func (*EventFilter) ProtoMessage()               {}
func (*EventFilter) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *EventFilter) GetSyscallEvents() []*SyscallEventFilter {
	if m != nil {
		return m.SyscallEvents
	}
	return nil
}

func (m *EventFilter) GetProcessEvents() []*ProcessEventFilter {
	if m != nil {
		return m.ProcessEvents
	}
	return nil
}

func (m *EventFilter) GetFileEvents() []*FileEventFilter {
	if m != nil {
		return m.FileEvents
	}
	return nil
}

func (m *EventFilter) GetContainerEvents() []*ContainerEventFilter {
	if m != nil {
		return m.ContainerEvents
	}
	return nil
}

func (m *EventFilter) GetChargenEvents() []*ChargenEventFilter {
	if m != nil {
		return m.ChargenEvents
	}
	return nil
}

func (m *EventFilter) GetTickerEvents() []*TickerEventFilter {
	if m != nil {
		return m.TickerEvents
	}
	return nil
}

type SyscallEventFilter struct {
	// Type of system call event (entry w/ args or exit w/ ret)
	Type SyscallEventType `protobuf:"varint,1,opt,name=type,enum=capsule8.api.v0.SyscallEventType" json:"type,omitempty"`
	// System call number (arch/x86/entry/syscalls/syscall_64.tbl)
	Id   *google_protobuf1.Int64Value  `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Arg0 *google_protobuf1.UInt64Value `protobuf:"bytes,10,opt,name=arg0" json:"arg0,omitempty"`
	Arg1 *google_protobuf1.UInt64Value `protobuf:"bytes,11,opt,name=arg1" json:"arg1,omitempty"`
	Arg2 *google_protobuf1.UInt64Value `protobuf:"bytes,12,opt,name=arg2" json:"arg2,omitempty"`
	Arg3 *google_protobuf1.UInt64Value `protobuf:"bytes,13,opt,name=arg3" json:"arg3,omitempty"`
	Arg4 *google_protobuf1.UInt64Value `protobuf:"bytes,14,opt,name=arg4" json:"arg4,omitempty"`
	Arg5 *google_protobuf1.UInt64Value `protobuf:"bytes,15,opt,name=arg5" json:"arg5,omitempty"`
	Ret  *google_protobuf1.Int64Value  `protobuf:"bytes,20,opt,name=ret" json:"ret,omitempty"`
}

func (m *SyscallEventFilter) Reset()                    { *m = SyscallEventFilter{} }
func (m *SyscallEventFilter) String() string            { return proto.CompactTextString(m) }
func (*SyscallEventFilter) ProtoMessage()               {}
func (*SyscallEventFilter) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *SyscallEventFilter) GetType() SyscallEventType {
	if m != nil {
		return m.Type
	}
	return SyscallEventType_SYSCALL_EVENT_TYPE_UNKNOWN
}

func (m *SyscallEventFilter) GetId() *google_protobuf1.Int64Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SyscallEventFilter) GetArg0() *google_protobuf1.UInt64Value {
	if m != nil {
		return m.Arg0
	}
	return nil
}

func (m *SyscallEventFilter) GetArg1() *google_protobuf1.UInt64Value {
	if m != nil {
		return m.Arg1
	}
	return nil
}

func (m *SyscallEventFilter) GetArg2() *google_protobuf1.UInt64Value {
	if m != nil {
		return m.Arg2
	}
	return nil
}

func (m *SyscallEventFilter) GetArg3() *google_protobuf1.UInt64Value {
	if m != nil {
		return m.Arg3
	}
	return nil
}

func (m *SyscallEventFilter) GetArg4() *google_protobuf1.UInt64Value {
	if m != nil {
		return m.Arg4
	}
	return nil
}

func (m *SyscallEventFilter) GetArg5() *google_protobuf1.UInt64Value {
	if m != nil {
		return m.Arg5
	}
	return nil
}

func (m *SyscallEventFilter) GetRet() *google_protobuf1.Int64Value {
	if m != nil {
		return m.Ret
	}
	return nil
}

type ProcessEventFilter struct {
	// Required; the process event type to match
	Type ProcessEventType `protobuf:"varint,1,opt,name=type,enum=capsule8.api.v0.ProcessEventType" json:"type,omitempty"`
}

func (m *ProcessEventFilter) Reset()                    { *m = ProcessEventFilter{} }
func (m *ProcessEventFilter) String() string            { return proto.CompactTextString(m) }
func (*ProcessEventFilter) ProtoMessage()               {}
func (*ProcessEventFilter) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *ProcessEventFilter) GetType() ProcessEventType {
	if m != nil {
		return m.Type
	}
	return ProcessEventType_PROCESS_EVENT_TYPE_UNKNOWN
}

type FileEventFilter struct {
	// Required
	Type FileEventType `protobuf:"varint,1,opt,name=type,enum=capsule8.api.v0.FileEventType" json:"type,omitempty"`
	// Optional filename exact match
	Filename *google_protobuf1.StringValue `protobuf:"bytes,10,opt,name=filename" json:"filename,omitempty"`
	// Optional filename pattern
	FilenamePattern *google_protobuf1.StringValue `protobuf:"bytes,11,opt,name=filename_pattern,json=filenamePattern" json:"filename_pattern,omitempty"`
	// Optional open(2) flags mask value
	OpenFlagsMask *google_protobuf1.Int32Value `protobuf:"bytes,12,opt,name=open_flags_mask,json=openFlagsMask" json:"open_flags_mask,omitempty"`
	// Optional open(2)/creat(2) mode mask value
	CreateModeMask *google_protobuf1.Int32Value `protobuf:"bytes,13,opt,name=create_mode_mask,json=createModeMask" json:"create_mode_mask,omitempty"`
}

func (m *FileEventFilter) Reset()                    { *m = FileEventFilter{} }
func (m *FileEventFilter) String() string            { return proto.CompactTextString(m) }
func (*FileEventFilter) ProtoMessage()               {}
func (*FileEventFilter) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *FileEventFilter) GetType() FileEventType {
	if m != nil {
		return m.Type
	}
	return FileEventType_FILE_EVENT_TYPE_UNKNOWN
}

func (m *FileEventFilter) GetFilename() *google_protobuf1.StringValue {
	if m != nil {
		return m.Filename
	}
	return nil
}

func (m *FileEventFilter) GetFilenamePattern() *google_protobuf1.StringValue {
	if m != nil {
		return m.FilenamePattern
	}
	return nil
}

func (m *FileEventFilter) GetOpenFlagsMask() *google_protobuf1.Int32Value {
	if m != nil {
		return m.OpenFlagsMask
	}
	return nil
}

func (m *FileEventFilter) GetCreateModeMask() *google_protobuf1.Int32Value {
	if m != nil {
		return m.CreateModeMask
	}
	return nil
}

type ContainerEventFilter struct {
	// Required, specify the particular type of event type to match
	Type ContainerEventType `protobuf:"varint,1,opt,name=type,enum=capsule8.api.v0.ContainerEventType" json:"type,omitempty"`
	// Optional, specifies how much detail to include in container events
	View ContainerEventView `protobuf:"varint,2,opt,name=view,enum=capsule8.api.v0.ContainerEventView" json:"view,omitempty"`
}

func (m *ContainerEventFilter) Reset()                    { *m = ContainerEventFilter{} }
func (m *ContainerEventFilter) String() string            { return proto.CompactTextString(m) }
func (*ContainerEventFilter) ProtoMessage()               {}
func (*ContainerEventFilter) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func (m *ContainerEventFilter) GetType() ContainerEventType {
	if m != nil {
		return m.Type
	}
	return ContainerEventType_CONTAINER_EVENT_TYPE_UNKNOWN
}

func (m *ContainerEventFilter) GetView() ContainerEventView {
	if m != nil {
		return m.View
	}
	return ContainerEventView_BASIC
}

type ChargenEventFilter struct {
	// Length of character sequence strings to generate
	Length uint64 `protobuf:"varint,1,opt,name=length" json:"length,omitempty"`
}

func (m *ChargenEventFilter) Reset()                    { *m = ChargenEventFilter{} }
func (m *ChargenEventFilter) String() string            { return proto.CompactTextString(m) }
func (*ChargenEventFilter) ProtoMessage()               {}
func (*ChargenEventFilter) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

func (m *ChargenEventFilter) GetLength() uint64 {
	if m != nil {
		return m.Length
	}
	return 0
}

type TickerEventFilter struct {
	// The interval at which ticker events are generated
	Interval int64 `protobuf:"varint,1,opt,name=interval" json:"interval,omitempty"`
}

func (m *TickerEventFilter) Reset()                    { *m = TickerEventFilter{} }
func (m *TickerEventFilter) String() string            { return proto.CompactTextString(m) }
func (*TickerEventFilter) ProtoMessage()               {}
func (*TickerEventFilter) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{9} }

func (m *TickerEventFilter) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

//
// Modifier specifies which stream modifiers to apply if any. For a given
// stream, a modifier can apply a throttle or limit etc. Modifiers can be
// used together.
//
type Modifier struct {
	Throttle *ThrottleModifier `protobuf:"bytes,1,opt,name=throttle" json:"throttle,omitempty"`
	Limit    *LimitModifier    `protobuf:"bytes,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *Modifier) Reset()                    { *m = Modifier{} }
func (m *Modifier) String() string            { return proto.CompactTextString(m) }
func (*Modifier) ProtoMessage()               {}
func (*Modifier) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{10} }

func (m *Modifier) GetThrottle() *ThrottleModifier {
	if m != nil {
		return m.Throttle
	}
	return nil
}

func (m *Modifier) GetLimit() *LimitModifier {
	if m != nil {
		return m.Limit
	}
	return nil
}

type ThrottleModifier struct {
	Interval     int64                         `protobuf:"varint,1,opt,name=interval" json:"interval,omitempty"`
	IntervalType ThrottleModifier_IntervalType `protobuf:"varint,2,opt,name=interval_type,json=intervalType,enum=capsule8.api.v0.ThrottleModifier_IntervalType" json:"interval_type,omitempty"`
}

func (m *ThrottleModifier) Reset()                    { *m = ThrottleModifier{} }
func (m *ThrottleModifier) String() string            { return proto.CompactTextString(m) }
func (*ThrottleModifier) ProtoMessage()               {}
func (*ThrottleModifier) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{11} }

func (m *ThrottleModifier) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *ThrottleModifier) GetIntervalType() ThrottleModifier_IntervalType {
	if m != nil {
		return m.IntervalType
	}
	return ThrottleModifier_MILLISECOND
}

type LimitModifier struct {
	// Limit the number of events
	Limit int64 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
}

func (m *LimitModifier) Reset()                    { *m = LimitModifier{} }
func (m *LimitModifier) String() string            { return proto.CompactTextString(m) }
func (*LimitModifier) ProtoMessage()               {}
func (*LimitModifier) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{12} }

func (m *LimitModifier) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func init() {
	proto.RegisterType((*Subscription)(nil), "capsule8.api.v0.Subscription")
	proto.RegisterType((*SensorFilter)(nil), "capsule8.api.v0.SensorFilter")
	proto.RegisterType((*ContainerFilter)(nil), "capsule8.api.v0.ContainerFilter")
	proto.RegisterType((*EventFilter)(nil), "capsule8.api.v0.EventFilter")
	proto.RegisterType((*SyscallEventFilter)(nil), "capsule8.api.v0.SyscallEventFilter")
	proto.RegisterType((*ProcessEventFilter)(nil), "capsule8.api.v0.ProcessEventFilter")
	proto.RegisterType((*FileEventFilter)(nil), "capsule8.api.v0.FileEventFilter")
	proto.RegisterType((*ContainerEventFilter)(nil), "capsule8.api.v0.ContainerEventFilter")
	proto.RegisterType((*ChargenEventFilter)(nil), "capsule8.api.v0.ChargenEventFilter")
	proto.RegisterType((*TickerEventFilter)(nil), "capsule8.api.v0.TickerEventFilter")
	proto.RegisterType((*Modifier)(nil), "capsule8.api.v0.Modifier")
	proto.RegisterType((*ThrottleModifier)(nil), "capsule8.api.v0.ThrottleModifier")
	proto.RegisterType((*LimitModifier)(nil), "capsule8.api.v0.LimitModifier")
	proto.RegisterEnum("capsule8.api.v0.ContainerEventView", ContainerEventView_name, ContainerEventView_value)
	proto.RegisterEnum("capsule8.api.v0.ProcessView", ProcessView_name, ProcessView_value)
	proto.RegisterEnum("capsule8.api.v0.ThrottleModifier_IntervalType", ThrottleModifier_IntervalType_name, ThrottleModifier_IntervalType_value)
}

func init() { proto.RegisterFile("capsule8/api/v0/subscription.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 1030 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x4d, 0x4f, 0xe3, 0x46,
	0x18, 0xde, 0xc4, 0x59, 0x14, 0x5e, 0xe7, 0xc3, 0x3b, 0xa2, 0x2b, 0x17, 0x28, 0xa5, 0x5e, 0xad,
	0x44, 0xb7, 0xad, 0xc3, 0x06, 0xe8, 0xee, 0xa1, 0x1f, 0x82, 0x6c, 0xd8, 0xa6, 0xcb, 0x97, 0x1c,
	0xa0, 0x52, 0x2f, 0x96, 0x71, 0x26, 0x61, 0x84, 0x63, 0x5b, 0x9e, 0x09, 0x88, 0x53, 0xaf, 0xfd,
	0x65, 0xbd, 0xf6, 0xd0, 0x1e, 0xfb, 0x63, 0x2a, 0xcf, 0x8c, 0x93, 0x49, 0x4c, 0x08, 0xb7, 0x79,
	0xdf, 0x79, 0x9e, 0xc7, 0x33, 0xef, 0xd7, 0x18, 0x2c, 0xdf, 0x8b, 0xe9, 0x28, 0xc0, 0xef, 0x1b,
	0x5e, 0x4c, 0x1a, 0xb7, 0xdb, 0x0d, 0x3a, 0xba, 0xa2, 0x7e, 0x42, 0x62, 0x46, 0xa2, 0xd0, 0x8e,
	0x93, 0x88, 0x45, 0xa8, 0x9e, 0x61, 0x6c, 0x2f, 0x26, 0xf6, 0xed, 0xf6, 0xea, 0xda, 0x2c, 0x09,
	0xdf, 0xe2, 0x90, 0x09, 0xf4, 0xea, 0xc6, 0x20, 0x8a, 0x06, 0x01, 0x6e, 0x70, 0xeb, 0x6a, 0xd4,
	0x6f, 0xdc, 0x25, 0x5e, 0x1c, 0xe3, 0x84, 0x8a, 0x7d, 0xeb, 0x3f, 0x0d, 0x2a, 0x5d, 0xe5, 0x23,
	0xe8, 0x67, 0xa8, 0x70, 0xbe, 0xdb, 0x27, 0x01, 0xc3, 0x89, 0x59, 0xd8, 0x2c, 0x6c, 0xe9, 0xcd,
	0x75, 0x7b, 0xe6, 0xab, 0x76, 0x3b, 0x05, 0x1d, 0x72, 0x8c, 0xa3, 0xe3, 0x89, 0x81, 0x3e, 0x81,
	0xe1, 0x47, 0x21, 0xf3, 0x48, 0x88, 0x93, 0x4c, 0xa4, 0xc8, 0x45, 0x36, 0x73, 0x22, 0xad, 0x0c,
	0x28, 0x85, 0xea, 0xfe, 0xb4, 0x03, 0x1d, 0x40, 0x95, 0xe2, 0x90, 0x46, 0x63, 0x25, 0x8d, 0x2b,
	0x7d, 0x91, 0x53, 0xea, 0x72, 0x94, 0x94, 0xa9, 0x50, 0xc5, 0x42, 0x07, 0x50, 0xa3, 0x24, 0xf4,
	0xb1, 0xdb, 0x1b, 0x25, 0x5e, 0x7a, 0x47, 0x13, 0xb8, 0xc8, 0x9a, 0x2d, 0x62, 0x63, 0x67, 0xb1,
	0xb1, 0x3b, 0x21, 0xfb, 0x7e, 0xf7, 0xd2, 0x0b, 0x46, 0xd8, 0xa9, 0x72, 0xca, 0x07, 0xc9, 0x40,
	0x3f, 0x41, 0xa5, 0x1f, 0x25, 0x13, 0x05, 0x7d, 0xb1, 0x82, 0xde, 0x8f, 0x92, 0x31, 0x7f, 0x0f,
	0xca, 0xc3, 0xa8, 0x47, 0xfa, 0x04, 0x27, 0xe6, 0x0a, 0xe7, 0x7e, 0x9e, 0xbb, 0xc2, 0xb1, 0x04,
	0x38, 0x63, 0x68, 0x9a, 0x8c, 0x38, 0x89, 0x7c, 0x4c, 0xa9, 0x7b, 0x4b, 0xf0, 0x9d, 0xb9, 0xb1,
	0x59, 0xd8, 0xaa, 0x3d, 0x90, 0x8c, 0x33, 0x01, 0xba, 0x24, 0xf8, 0xce, 0xd1, 0xe3, 0x89, 0x61,
	0xd5, 0xa0, 0xa2, 0x46, 0xc6, 0xba, 0x83, 0xfa, 0x4c, 0xcc, 0x91, 0x01, 0x1a, 0xe9, 0x51, 0xb3,
	0xb0, 0xa9, 0x6d, 0x2d, 0x3b, 0xe9, 0x12, 0xad, 0xc0, 0xf3, 0xd0, 0x1b, 0x62, 0x6a, 0x16, 0xb9,
	0x4f, 0x18, 0x68, 0x0d, 0x96, 0xc9, 0xd0, 0x1b, 0x60, 0x37, 0x45, 0x6b, 0x7c, 0xa7, 0xcc, 0x1d,
	0x9d, 0x1e, 0x45, 0x5f, 0x82, 0x2e, 0x36, 0x05, 0xb1, 0xc4, 0xb7, 0x81, 0xbb, 0x4e, 0x52, 0x8f,
	0xf5, 0xb7, 0x06, 0xba, 0x52, 0x32, 0xe8, 0x57, 0xa8, 0xd1, 0x7b, 0xea, 0x7b, 0x41, 0xe0, 0xf2,
	0xe2, 0x11, 0x07, 0xd0, 0x9b, 0xaf, 0xf2, 0x99, 0x15, 0x30, 0xb5, 0xde, 0xaa, 0x54, 0xf1, 0xd1,
	0x54, 0x2b, 0x8b, 0x92, 0xd4, 0x2a, 0xce, 0xd1, 0x92, 0x71, 0x9a, 0xd2, 0x8a, 0x15, 0x1f, 0x45,
	0xfb, 0xa0, 0xf7, 0x49, 0x80, 0x33, 0x21, 0x8d, 0x0b, 0xe5, 0x0b, 0xf7, 0x90, 0x04, 0x58, 0x55,
	0x81, 0x7e, 0xe6, 0xa0, 0xe8, 0x4c, 0x6d, 0x00, 0xa9, 0x03, 0x5c, 0xe7, 0xf5, 0xfc, 0x06, 0x50,
	0xc5, 0x26, 0x5d, 0x30, 0xb9, 0xa0, 0x7f, 0xed, 0x25, 0x03, 0x1c, 0x66, 0x7a, 0xbd, 0x39, 0x17,
	0x6c, 0x09, 0xd8, 0xd4, 0x05, 0x7d, 0xc5, 0x47, 0xd1, 0x47, 0xa8, 0x32, 0xe2, 0xdf, 0x4c, 0x8e,
	0x86, 0xb9, 0x94, 0x95, 0x93, 0x3a, 0xe7, 0x28, 0x55, 0xa9, 0xc2, 0x26, 0x2e, 0x6a, 0xfd, 0xa3,
	0x01, 0xca, 0xe7, 0x06, 0xed, 0x41, 0x89, 0xdd, 0xc7, 0x98, 0xcf, 0x8d, 0x5a, 0xf3, 0xab, 0x47,
	0xd3, 0x79, 0x7e, 0x1f, 0x63, 0x87, 0xc3, 0xd1, 0x37, 0x50, 0x24, 0x3d, 0x39, 0x27, 0x1e, 0x6d,
	0xab, 0x22, 0xe9, 0xa1, 0x6d, 0x28, 0x79, 0xc9, 0x60, 0x5b, 0xf6, 0xf1, 0x7a, 0x0e, 0x7e, 0xa1,
	0xe0, 0x39, 0x52, 0x32, 0xde, 0xca, 0xbe, 0x5d, 0xcc, 0x78, 0x2b, 0x19, 0x4d, 0xb3, 0xf2, 0x44,
	0x46, 0x53, 0x32, 0x76, 0xcc, 0xea, 0x13, 0x19, 0x3b, 0x92, 0xb1, 0x6b, 0xd6, 0x9e, 0xc8, 0xd8,
	0x95, 0x8c, 0x3d, 0xb3, 0xfe, 0x44, 0xc6, 0x1e, 0xfa, 0x0e, 0xb4, 0x04, 0x33, 0x39, 0x74, 0x1e,
	0x8d, 0x6c, 0x8a, 0xb3, 0x3e, 0x01, 0xca, 0x37, 0xc9, 0xc2, 0xa4, 0xaa, 0x94, 0x49, 0x52, 0xad,
	0x7f, 0x8b, 0x50, 0x9f, 0xe9, 0x14, 0xd4, 0x9c, 0x92, 0xda, 0x98, 0xdf, 0x59, 0x4a, 0x71, 0xbc,
	0x87, 0x72, 0xda, 0x5f, 0xe9, 0x6c, 0x99, 0x9b, 0xf3, 0x2e, 0x4b, 0x48, 0x38, 0x10, 0x37, 0x19,
	0xa3, 0xd1, 0x47, 0x30, 0xb2, 0xb5, 0x1b, 0x7b, 0x8c, 0xe1, 0x24, 0x9c, 0x5b, 0x03, 0xaa, 0x42,
	0x3d, 0x63, 0x9d, 0x09, 0x12, 0x6a, 0x41, 0x3d, 0x8a, 0x71, 0xe8, 0xf6, 0x03, 0x6f, 0x40, 0xdd,
	0xa1, 0x47, 0x6f, 0x64, 0x65, 0x3c, 0x18, 0xd2, 0x9d, 0xa6, 0x7c, 0x45, 0x52, 0xce, 0x61, 0x4a,
	0x39, 0xf6, 0xe8, 0x0d, 0x6a, 0x83, 0xe1, 0x27, 0xd8, 0x63, 0xd8, 0x1d, 0x46, 0x3d, 0x2c, 0x54,
	0xaa, 0x8b, 0x55, 0x6a, 0x82, 0x74, 0x1c, 0xf5, 0x70, 0x2a, 0x63, 0xfd, 0x59, 0x80, 0x95, 0x87,
	0x06, 0x07, 0x7a, 0x37, 0x15, 0xdb, 0x57, 0x0b, 0xa6, 0x8d, 0x12, 0xe0, 0x77, 0x50, 0xe2, 0xef,
	0x4b, 0xf1, 0x49, 0x44, 0xfe, 0xcc, 0x70, 0x82, 0xf5, 0x2d, 0xa0, 0xfc, 0xc8, 0x41, 0x2f, 0x61,
	0x29, 0xc0, 0xe1, 0x80, 0x5d, 0xf3, 0x93, 0x94, 0x1c, 0x69, 0x59, 0x0d, 0x78, 0x91, 0x9b, 0x2a,
	0x68, 0x15, 0xca, 0x24, 0x64, 0x38, 0xb9, 0xf5, 0x02, 0x0e, 0xd7, 0x9c, 0xb1, 0x6d, 0xfd, 0x01,
	0xe5, 0xec, 0x55, 0x44, 0x3f, 0x42, 0x99, 0x5d, 0x27, 0x11, 0x63, 0x01, 0x96, 0x3f, 0x25, 0xf9,
	0x3a, 0x3c, 0x97, 0x80, 0xc9, 0x53, 0x9a, 0x51, 0xd0, 0x2e, 0x3c, 0x0f, 0xc8, 0x90, 0x30, 0x39,
	0x63, 0xf2, 0x85, 0x77, 0x94, 0xee, 0x8e, 0x89, 0x02, 0x6c, 0xfd, 0x55, 0x00, 0x63, 0x56, 0xf4,
	0xb1, 0x13, 0xa3, 0x2e, 0x54, 0xb3, 0xb5, 0xcb, 0x73, 0x21, 0x42, 0x6a, 0x2f, 0x3c, 0x6a, 0x9a,
	0x70, 0x4e, 0xe3, 0x69, 0xa9, 0x10, 0xc5, 0xb2, 0xf6, 0xa1, 0xa2, 0xee, 0xa2, 0x3a, 0xe8, 0xc7,
	0x9d, 0xa3, 0xa3, 0x4e, 0xb7, 0xdd, 0x3a, 0x3d, 0xf9, 0x60, 0x3c, 0x43, 0x00, 0x4b, 0x72, 0x5d,
	0x48, 0xd7, 0xc7, 0x9d, 0x93, 0x8b, 0xf3, 0xb6, 0x51, 0x44, 0x65, 0x28, 0xfd, 0x72, 0x7a, 0xe1,
	0x18, 0x9a, 0xf5, 0x1a, 0xaa, 0x53, 0x17, 0x4c, 0x1f, 0x79, 0x11, 0x0f, 0x71, 0x03, 0x61, 0xbc,
	0xf9, 0x1a, 0x50, 0x3e, 0xd7, 0x68, 0x19, 0x9e, 0x1f, 0xec, 0x77, 0x3b, 0x2d, 0xe3, 0x59, 0xaa,
	0x78, 0x78, 0x71, 0x74, 0x64, 0x14, 0xde, 0xfc, 0x00, 0xba, 0xf2, 0xdb, 0x81, 0x5e, 0x02, 0x3a,
	0x73, 0x4e, 0x5b, 0xed, 0x6e, 0xd7, 0xbd, 0xec, 0xb4, 0x7f, 0x73, 0x33, 0xc2, 0x67, 0xf0, 0x62,
	0xca, 0x2f, 0xd8, 0x07, 0xeb, 0xbf, 0xaf, 0x0e, 0x08, 0xbb, 0x1e, 0x5d, 0xd9, 0x7e, 0x34, 0x6c,
	0xcc, 0xfc, 0xc1, 0x5e, 0x2d, 0xf1, 0x36, 0xd8, 0xf9, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x39,
	0x78, 0x1e, 0x10, 0x0b, 0x00, 0x00,
}
